name: Build Laravel App

on: workflow_call

jobs:
  build:
    name: Build Laravel App
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          composer install
      - name: Cache Primes
        uses: actions/cache@v4
        with:
          key: php-vendor-cache
          path: ./vendor
      - name: Setup Env
        run: |
          cp .env.ci .env
          cp .env.ci .env.testing
      - name: Generate the Key
        run: |
          php artisan key:generate
