name: Main Workflow

on:
  push:
  pull_request:
    branches:
      - dev
      - main

env:
  PORT: 3000

jobs:
  build:
    name: "Build"
    uses: ./github/workflows/build.yaml
     
  test:
    name: "Test"
    uses: ./github/workflows/test.yaml