name: Test the Application

on: workflow_call

jobs:
  test:
    name: Test the application
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password 
          MYSQL_USERNAME: root
          MYSQL_DATABASE: test 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - name: Restore the cache
        uses: actions/cache@v4
        with:
          path: ./vendor
          key: php-vendor-cache
      - name: Composer Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          composer install
      - name: Setup Env
        run: |
          cp .env.ci .env
      - name: Migrate the database
        run: |
          php artisan migrate
      - name: Run Unit Test
        run: |
          php artisan test